apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "php.fullname" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.laravel.env.APP_NAME | quote }}
  APP_ENV: {{ .Values.laravel.env.APP_ENV | quote }}
  APP_DEBUG: {{ .Values.laravel.env.APP_DEBUG | quote }}
  APP_URL: {{ .Values.laravel.env.APP_URL | quote }}
  
  LOG_CHANNEL: {{ .Values.laravel.env.LOG_CHANNEL | quote }}
  LOG_DEPRECATIONS_CHANNEL: {{ .Values.laravel.env.LOG_DEPRECATIONS_CHANNEL | quote }}
  LOG_LEVEL: {{ .Values.laravel.env.LOG_LEVEL | quote }}
  
  DB_CONNECTION: {{ .Values.laravel.env.DB_CONNECTION | quote }}
  DB_HOST: {{ .Values.laravel.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.laravel.env.DB_PORT | quote }}
  DB_DATABASE: {{ .Values.laravel.env.DB_DATABASE | quote }}
  DB_USERNAME: {{ .Values.laravel.env.DB_USERNAME | quote }}
  
  BROADCAST_DRIVER: {{ .Values.laravel.env.BROADCAST_DRIVER | quote }}
  CACHE_DRIVER: {{ .Values.laravel.env.CACHE_DRIVER | quote }}
  FILESYSTEM_DRIVER: {{ .Values.laravel.env.FILESYSTEM_DRIVER | quote }}
  QUEUE_CONNECTION: {{ .Values.laravel.env.QUEUE_CONNECTION | quote }}
  SANCTUM_STATEFUL_DOMAINS: {{ .Values.laravel.env.SANCTUM_STATEFUL_DOMAINS | quote }}
  SESSION_DOMAIN: {{ .Values.laravel.env.SESSION_DOMAIN | quote }}
  SESSION_DRIVER: {{ .Values.laravel.env.SESSION_DRIVER | quote }}
  SESSION_LIFETIME: {{ .Values.laravel.env.SESSION_LIFETIME | quote }}
  
  REDIS_HOST: {{ .Values.laravel.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.laravel.env.REDIS_PORT | quote }}
