apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "php.fullname" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
  {{- with .Values.cronjob.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  {{- with .Values.cronjob.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        {{- /*
        metadata:
          labels:
            {{- include "php.selectorLabels" . | nindent 12 }}
        */}}
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - |
                  rm -rf /var/www/{{ .Values.laravel.directory }}/vendor && composer install --optimize-autoloader && composer dump-autoload
                  chmod -R 775 /var/www/{{ .Values.laravel.directory }}/artisan && chmod -R 777 /var/www/{{ .Values.laravel.directory }}/storage && find /var/www/{{ .Values.laravel.directory }}/storage/ -type f -name ".gitignore" -exec chmod 664 {} \;
                  /var/www/{{ .Values.laravel.directory }}/artisan migrate:refresh --seed
              envFrom:
                - configMapRef:
                    name: {{ include "php.fullname" . }}
                - secretRef:
                    name: {{ include "php.fullname" . }}
