apiVersion: v1
kind: Secret
metadata:
  name: {{ include "php.fullname" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: {{ .Values.laravel.env.APP_KEY | b64enc | quote }}
  DB_PASSWORD: {{ .Values.laravel.env.DB_PASSWORD | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.laravel.env.REDIS_PASSWORD | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.laravel.env.MAIL_PASSWORD | quote }}
